sudo: required

matrix:
  include:
    - os: linux
      dist: xenial

language: python
python: "3.5"

before_install:
  - sudo apt-get update -qq

install:
  - pip install ansible

script:
- ansible-playbook -i inventory  main.yml  --syntax-check
- ansible-playbook -i inventory  main.yml
