---
- name: Install Docker
  become: true
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - apt-transport-https
    - "ca-certificates"
    - "curl"
    - "software-properties-common"
# - name: add GPG key
#   become: true
#   apt_key:
#     url: https://download.docker.com/linux/ubuntu/gpg
#     validate_certs: no
#     state: present
- name: Install gpg key
  command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg |  apt-key add -
- name: add apt repository
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
- name: Install Docker-ce package
  become: true
  apt:
    name: docker-ce
    update_cache: yes
