---
- name: Download go
  become: true
  unarchive:
    src: https://dl.google.com/go/go1.10.linux-amd64.tar.gz
    dest: /usr/local
    remote_src: yes
- name: Add Go to path
  lineinfile:
    path: ~/.bashrc
    regexp: 'export\s+PATH=\$PATH:\/usr\/local\/go\/bin'
    line: 'export PATH=$PATH:/usr/local/go/bin'
    insertafter: 'EOF'
